# Generated by Django 4.1.1 on 2022-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('posicion', models.CharField(max_length=100)),
                ('permisos', models.CharField(max_length=12)),
                ('nsfw', models.BooleanField()),
                ('limiteusuarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=12)),
                ('contraseña', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('permisos', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=12)),
                ('canales', models.ManyToManyField(to='authApp.canal')),
                ('creador', models.ManyToManyField(to='authApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=300)),
                ('hora_envio', models.DateTimeField()),
                ('reaccion', models.CharField(max_length=12)),
                ('menciones', models.CharField(max_length=12)),
                ('autor', models.ManyToManyField(to='authApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField()),
                ('autor', models.ManyToManyField(to='authApp.usuario')),
                ('canal', models.ManyToManyField(to='authApp.canal')),
                ('server', models.ManyToManyField(to='authApp.servidor')),
            ],
        ),
    ]
